source 'https://rubygems.org'
# gem 'github-pages', group: :jekyll_plugins
gem 'jekyll', '3.1.6'
gem 'jekyll-sass-converter', '1.3.0'
gem 'kramdown', '1.11.1'
gem 'liquid', '3.0.6'
gem 'rouge', '1.10.1'
gem 'github-pages-health-check', '1.1.0'
gem 'jemoji', '0.6.2'
gem 'jekyll-mentions', '1.1.3'
gem 'jekyll-redirect-from', '0.10.0'
gem 'jekyll-sitemap', '0.10.0'
gem 'jekyll-feed', '0.5.1'
gem 'jekyll-gist', '1.4.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-seo-tag', '2.0.0'
gem 'jekyll-github-metadata', '2.0.2'
gem 'listen', '3.0.6'
